# Generated by Django 3.1.6 on 2021-04-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(upload_to='games_app/')),
                ('file', models.FileField(upload_to='documents/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_app.category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.publisher')),
            ],
        ),
    ]
