# Generated by Django 3.1.6 on 2021-05-03 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
    ]
